import jsPDF from 'jspdf';
import QRCode from 'qrcode';

export const generateTicketPDF = async (booking, bus) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    // Helper to draw horizontal line
    const line = (y) => {
        doc.setDrawColor(200);
        doc.line(10, y, 200, y);
    };

    // HEADER
    doc.setFillColor(79, 70, 229); // Indigo-600
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    doc.text('BUS BOOKING TICKET', 105, 15, { align: 'center' });

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Booking ID: ${booking.bookingId}`, 105, 25, { align: 'center' });
    doc.text(`Status: ${booking.Status || 'Confirmed'}`, 105, 30, { align: 'center' });

    // BODY
    doc.setTextColor(50, 50, 50);
    let y = 50;

    // Bus Details Section
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('BUS DETAILS', 15, y);
    y += 8;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Bus Name: ${bus.busName}`, 15, y);
    doc.text(`Bus Number: ${bus.busNumber}`, 120, y);
    y += 10;
    line(y);
    y += 10;

    // Journey Section
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('JOURNEY INFORMATION', 15, y);
    y += 8;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`From: ${booking.from}`, 15, y);
    doc.text(`To: ${booking.to}`, 120, y);
    y += 8;

    const departureDate = new Date(bus.startDateTime);
    const arrivalDate = new Date(bus.endDateTime);

    doc.text(`Departure: ${departureDate.toLocaleDateString()} ${departureDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`, 15, y);
    doc.text(`Arrival: ${arrivalDate.toLocaleDateString()} ${arrivalDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`, 120, y);
    y += 10;
    line(y);
    y += 10;

    // Passenger & Fare Section
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('BOOKING DETAILS', 15, y);
    y += 8;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Seats Booked: ${booking.seatsBooked}`, 15, y);
    doc.text(`Payment Method: ${booking.paymentMethod === 'online' ? 'Online Payment' : 'Cash on Boarding'}`, 120, y);
    y += 8;
    doc.text(`Fare per Seat: RS ${booking.farePerSeat}`, 15, y);
    doc.setFont('helvetica', 'bold');
    doc.text(`Total Amount: RS ${booking.totalFare}`, 120, y);
    y += 12;
    line(y);
    y += 15;

    // QR CODE
    try {
        const qrData = JSON.stringify({
            id: booking.bookingId,
            bus: bus.busNumber,
            from: booking.from,
            to: booking.to,
            seats: booking.seatsBooked
        });
        const qrDataUrl = await QRCode.toDataURL(qrData);
        doc.addImage(qrDataUrl, 'PNG', 150, y - 5, 40, 40);

        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text('SCAN QR FOR VERIFICATION', 170, y + 40, { align: 'center' });
    } catch (err) {
        console.error('QR Code generation failed', err);
    }

    // Footer/Important Info
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('IMPORTANT INFORMATION', 15, y);
    y += 8;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text('• Please arrive at the boarding point at least 30 minutes before departure.', 15, y);
    y += 5;
    doc.text('• Carry a valid government-issued ID proof during the journey.', 15, y);
    y += 5;
    doc.text('• This e-ticket is valid only for the specified bus, date, and time.', 15, y);
    y += 5;
    doc.text('• For any queries, please contact our 24/7 support line.', 15, y);

    // Bottom Line
    doc.setDrawColor(79, 70, 229);
    doc.setLineWidth(1);
    doc.line(0, 280, 210, 280);

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by BusBooking App on ' + new Date().toLocaleString(), 105, 290, { align: 'center' });

    // SAVE
    doc.save(`Ticket_${booking.bookingId}.pdf`);
};
